const app=document.getElementById('app');
const demo={student:{name:'Mariana López',id:'EA-0001',plan:'Paquete Mensual',valid:'30/09/2026',next:'$499',classes:['Ballet · Lunes 6:00 PM','Jazz · Miércoles 5:00 PM']},admin:{name:'Administradora'}};
function logo(){return '<div class="logo">E</div>'}
function login(){app.innerHTML=`<main class="shell"><section class="content login">${logo()}<div class="title">EmpoderArte</div><div class="sub">Escuela de Danza · App</div><div class="field"><label>Correo electrónico</label><input id="email" type="email" placeholder="correo@ejemplo.com"></div><div class="field"><label>Contraseña</label><input id="pass" type="password" placeholder="••••••••"></div><button class="btn full" onclick="doLogin()">Iniciar sesión</button><p class="sub" style="margin-top:18px;font-size:12px">Demo: cualquier correo y contraseña</p></section></main>`}
function doLogin(){const admin=document.getElementById('email').value.toLowerCase().includes('admin');sessionStorage.role=admin?'admin':'student';render()}
function header(title){return `<header class="top"><div class="brand">EMPODERARTE</div><div class="row"><span class="muted">${title}</span><button class="btn alt" onclick="logout()">Salir</button></div></header>`}
function nav(active){return `<nav class="nav"><button class="${active==='home'?'active':''}" onclick="render('home')">Inicio</button><button class="${active==='attendance'?'active':''}" onclick="render('attendance')">Asistencias</button><button class="${active==='payments'?'active':''}" onclick="render('payments')">Pagos</button><button class="${active==='profile'?'active':''}" onclick="render('profile')">Perfil</button></nav>`}
function studentPage(page='home'){let s=demo.student;let body='';if(page==='home')body=`<h1>Hola, ${s.name.split(' ')[0]} 👋</h1><p class="muted">Tu información de EmpoderArte en un solo lugar.</p><div class="grid"><div class="card"><div class="muted">Plan o paquete activo</div><div class="big gold">${s.plan}</div><p class="muted">Vigencia hasta ${s.valid}</p></div><div class="card"><div class="muted">Próximo pago</div><div class="big">${s.next}</div><p class="muted">Vence el 30/09/2026</p><button class="btn" onclick="render('payments')">Pagar ahora</button></div></div><div class="card" style="margin-top:16px"><h3>Próximas clases</h3>${s.classes.map(x=>`<div class="notice">${x}</div>`).join('')}</div>`;if(page==='attendance')body=`<h1>Mis asistencias</h1><div class="grid"><div class="card"><div class="muted">Septiembre</div><div class="big gold">18 asistencias</div></div><div class="card"><div class="muted">Faltas</div><div class="big">2</div></div></div><div class="card" style="margin-top:16px"><table class="table"><tr><th>Fecha</th><th>Clase</th><th>Estado</th></tr><tr><td>23 Sep</td><td>Jazz</td><td class="gold">✓ Asistió</td></tr><tr><td>22 Sep</td><td>Ballet</td><td class="gold">✓ Asistió</td></tr><tr><td>20 Sep</td><td>Hip Hop</td><td>✕ Falta</td></tr></table></div>`;if(page==='payments')body=`<h1>Pagos</h1><div class="card"><div class="muted">Mensualidad de septiembre</div><div class="big gold">$499</div><p class="muted">Selecciona una forma de pago.</p><div class="grid"><button class="btn" onclick="alert('Aquí conectaremos el pago con tarjeta.')">💳 Tarjeta</button><button class="btn alt" onclick="alert('Aquí mostraremos los datos bancarios y carga de comprobante.')">🏦 Transferencia</button><button class="btn alt" onclick="alert('El administrador registrará el pago en efectivo.')">💵 Efectivo</button></div></div><div class="card" style="margin-top:16px"><h3>Historial</h3><p class="muted">Agosto · $499 · Pagado</p><p class="muted">Julio · $499 · Pagado</p></div>`;if(page==='profile')body=`<h1>Mi perfil</h1><div class="card"><div class="big">${s.name}</div><p class="muted">Número de alumno: ${s.id}</p><p>Plan: <span class="gold">${s.plan}</span></p><p>Vigencia: ${s.valid}</p><p>Correo: alumno@empoderarte.mx</p><button class="btn alt">Editar información</button></div>`;app.innerHTML=`<main class="shell">${header('Área del alumno')}<section class="content">${body}</section>${nav(page)}</main>`}
function adminPage(){app.innerHTML=`<main class="shell">${header('Administración')}<section class="content"><h1>Panel administrativo</h1><p class="muted">Vista inicial de EmpoderArte.</p><div class="grid"><div class="card"><div class="muted">Alumnos</div><div class="big gold">247</div></div><div class="card"><div class="muted">Asistencias hoy</div><div class="big">183</div></div><div class="card"><div class="muted">Pagos recibidos</div><div class="big">$18,450</div></div><div class="card"><div class="muted">Pagos pendientes</div><div class="big">32</div></div></div><div class="grid" style="margin-top:16px"><div class="card"><h3>👥 Alumnos</h3><p class="muted">Registrar, editar y consultar alumnos.</p></div><div class="card"><h3>💰 Pagos</h3><p class="muted">Registrar pagos y revisar comprobantes.</p></div><div class="card"><h3>📅 Clases</h3><p class="muted">Crear horarios y asignar profesores.</p></div><div class="card"><h3>📢 Avisos</h3><p class="muted">Enviar comunicados a los alumnos.</p></div></div></section></main>`}
function render(page='home'){if(!sessionStorage.role)return login();if(sessionStorage.role==='admin')return adminPage();studentPage(page)}function logout(){sessionStorage.clear();login()}render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
